version: "3"
services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./sample:/go/src/github.com/sample
    tty: true
    environment:
      - TZ=Asia/Tokyo
