version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    tty: true
    ports:
      - 1323:1323
    volumes:
      - .:/go/src/app
  database:
    image: postgres:latest
    container_name: test-container
    hostname: test-host
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: database
